"""test detection

Revision ID: 159e6d0a8178
Revises: b3ac32964f9b
Create Date: 2025-12-17 19:20:26.833650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159e6d0a8178'
down_revision: Union[str, Sequence[str], None] = 'b3ac32964f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_class_ranges',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
                    sa.Column('min_score', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['test_categories.id'],
                                            name=op.f('assessment_class_ranges_category_id_fkey'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('assessment_class_ranges_pkey'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(op.f('assessment_class_ranges'))
    # ### end Alembic commands ###
