"""add survey_options table

Revision ID: 25a14a2615c7
Revises: 11b65dffd788
Create Date: 2025-12-11 22:19:14.911972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a14a2615c7'
down_revision: Union[str, Sequence[str], None] = '11b65dffd788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Enum('very_low', 'low', 'neutral', 'medium', 'high', name='options'), nullable=False),
    sa.Column('weightage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('question_results', sa.Column('user_answer_audio', sa.LargeBinary(), nullable=True))
    op.add_column('question_results', sa.Column('user_answer_text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_results', 'user_answer_text')
    op.drop_column('question_results', 'user_answer_audio')
    op.drop_table('survey_options')
    # ### end Alembic commands ###
