"""add test_level to test_attempt

Revision ID: 3b5fcabc9ec4
Revises: 159e6d0a8178
Create Date: 2025-12-26 17:14:31.650720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b5fcabc9ec4'
down_revision: Union[str, Sequence[str], None] = '159e6d0a8178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_class_ranges')
    op.add_column('test_attempts', sa.Column('test_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'NORMAL', name='testlevel'), nullable=True))
    op.drop_column('test_attempts', 'overall_emotion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempts', sa.Column('overall_emotion', postgresql.ENUM('happy', 'sad', 'angry', 'fear', 'neutral', 'surprise', 'disgust', name='emotiontype'), autoincrement=False, nullable=True))
    op.drop_column('test_attempts', 'test_level')
    op.create_table('assessment_class_ranges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('min_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['test_categories.id'], name=op.f('assessment_class_ranges_category_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_class_ranges_pkey'))
    )
    # ### end Alembic commands ###
