"""add class range table 

Revision ID: 780d93db0c47
Revises: 25a14a2615c7
Create Date: 2025-12-14 20:26:26.053224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '780d93db0c47'
down_revision: Union[str, Sequence[str], None] = '25a14a2615c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_results', sa.Column('selected_option_id', sa.Integer(), nullable=True))
    op.alter_column('question_results', 'user_answer_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'question_results', 'survey_options', ['selected_option_id'], ['id'], ondelete='SET NULL')
    op.add_column('survey_options', sa.Column('category_id', sa.Integer(), nullable=False))
    op.alter_column('survey_options', 'option_text',
               existing_type=postgresql.ENUM('very_low', 'low', 'neutral', 'medium', 'high', name='options'),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('survey_options_question_id_fkey'), 'survey_options', type_='foreignkey')
    op.create_foreign_key(None, 'survey_options', 'test_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('survey_options', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_options', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'survey_options', type_='foreignkey')
    op.create_foreign_key(op.f('survey_options_question_id_fkey'), 'survey_options', 'questions', ['question_id'], ['id'])
    op.alter_column('survey_options', 'option_text',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('very_low', 'low', 'neutral', 'medium', 'high', name='options'),
               existing_nullable=False)
    op.drop_column('survey_options', 'category_id')
    op.drop_constraint(None, 'question_results', type_='foreignkey')
    op.alter_column('question_results', 'user_answer_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('question_results', 'selected_option_id')
    # ### end Alembic commands ###
