"""change test_attempt_field

Revision ID: 7db7ea1232f0
Revises: 159e6d0a8178
Create Date: 2025-12-26 20:59:26.196324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7db7ea1232f0'
down_revision: Union[str, Sequence[str], None] = '159e6d0a8178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('test_attempts', 'overall_emotion',
               existing_type=postgresql.ENUM('happy', 'sad', 'angry', 'fear', 'neutral', 'surprise', 'disgust', name='emotiontype'),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_attempts', 'overall_emotion',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('happy', 'sad', 'angry', 'fear', 'neutral', 'surprise', 'disgust', name='emotiontype'),
               existing_nullable=True)

    # ### end Alembic commands ###
