"""empty message

Revision ID: 8b6f4145b5a1
Revises: ffba78dc9817
Create Date: 2026-01-19 14:09:43.936066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6f4145b5a1'
down_revision: Union[str, Sequence[str], None] = 'ffba78dc9817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_results', sa.Column('emotion_probabilities', sa.JSON(), nullable=True))
    op.drop_column('question_results', 'recognized_emotion')
    op.drop_column('question_results', 'confidence')
    op.add_column('test_attempts', sa.Column('mental_health_score', sa.Float(), nullable=True))
    op.add_column('test_attempts', sa.Column('mental_health_state', sa.String(length=300), nullable=True))
    op.drop_column('test_attempts', 'overall_emotion')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('test_attempts', 'mental_health_state')
    op.drop_column('test_attempts', 'mental_health_score')
    op.drop_column('question_results', 'emotion_probabilities')

    # ### end Alembic commands ###
