"""empty message

Revision ID: ab9b3a4b69ea
Revises: 8109ae67dc41
Create Date: 2026-04-10 20:38:56.334866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab9b3a4b69ea'
down_revision: Union[str, Sequence[str], None] = '8109ae67dc41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempts', sa.Column('test_state', sa.Text(), nullable=True))
    op.drop_column('test_attempts', 'test_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempts', sa.Column('test_level', postgresql.ENUM('LOW', 'MODERATE', 'HIGH', 'NORMAL', name='testlevel'), autoincrement=False, nullable=True))
    op.drop_column('test_attempts', 'test_state')
    # ### end Alembic commands ###
