"""empty message

Revision ID: ffba78dc9817
Revises: 7db7ea1232f0
Create Date: 2026-01-17 19:26:01.345059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffba78dc9817'
down_revision: Union[str, Sequence[str], None] = '7db7ea1232f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # CORRECT
    op.add_column('users', sa.Column('name', sa.String(50), server_default='unknown', nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), server_default='unknown',nullable=False))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'name')

    # ### end Alembic commands ###
